title: pat.social
baseurl: ""
url: "https://pat.social"
twitter_username: pat

theme: minima

plugins:
  - jekyll-redirect-from

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
